spring.application.name=SmartHomeDeviceSystemManagement
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/device_system
spring.datasource.username=root
spring.datasource.password=UG%btcs@58
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver